FROM nginx

COPY symfony.conf /etc/nginx/conf.d/default.conf

# Update the upstream configuration to point to the correct PHP service
RUN echo "upstream php-upstream { server php-newrelic:9000; }" > /etc/nginx/conf.d/upstream.conf

# Set the correct permissions for the log directory
RUN chown -R www-data:www-data /var/log/nginx

HEALTHCHECK --interval=30s --timeout=5s \
  CMD curl -f http://localhost/ || exit 1
