<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;
use Commercetools\Base\JsonObjectModel;
use Commercetools\Base\MapperFactory;
use stdClass;

/**
 * @internal
 */
final class CartSetRecurringPaymentConfigurationActionModel extends JsonObjectModel implements CartSetRecurringPaymentConfigurationAction
{
    public const DISCRIMINATOR_VALUE = 'setRecurringPaymentConfiguration';
    /**
     *
     * @var ?string
     */
    protected $action;

    /**
     *
     * @var ?RecurringPaymentConfigurationDraft
     */
    protected $recurringPaymentConfiguration;


    /**
     * @psalm-suppress MissingParamType
     */
    public function __construct(
        ?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration = null,
        ?string $action = null
    ) {
        $this->recurringPaymentConfiguration = $recurringPaymentConfiguration;
        $this->action = $action ?? self::DISCRIMINATOR_VALUE;
    }

    /**
     *
     * @return null|string
     */
    public function getAction()
    {
        if (is_null($this->action)) {
            /** @psalm-var ?string $data */
            $data = $this->raw(self::FIELD_ACTION);
            if (is_null($data)) {
                return null;
            }
            $this->action = (string) $data;
        }

        return $this->action;
    }

    /**
     * <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="ctp:api:type:RecurringOrder">RecurringOrder</a> are created without collecting payment first.</p>
     *
     *
     * @return null|RecurringPaymentConfigurationDraft
     */
    public function getRecurringPaymentConfiguration()
    {
        if (is_null($this->recurringPaymentConfiguration)) {
            /** @psalm-var stdClass|array<string, mixed>|null $data */
            $data = $this->raw(self::FIELD_RECURRING_PAYMENT_CONFIGURATION);
            if (is_null($data)) {
                return null;
            }

            $this->recurringPaymentConfiguration = RecurringPaymentConfigurationDraftModel::of($data);
        }

        return $this->recurringPaymentConfiguration;
    }


    /**
     * @param ?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration
     */
    public function setRecurringPaymentConfiguration(?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration): void
    {
        $this->recurringPaymentConfiguration = $recurringPaymentConfiguration;
    }
}
