<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;

interface CartSetRecurringPaymentConfigurationAction extends CartUpdateAction
{
    public const FIELD_RECURRING_PAYMENT_CONFIGURATION = 'recurringPaymentConfiguration';

    /**
     * <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="ctp:api:type:RecurringOrder">RecurringOrder</a> are created without collecting payment first.</p>
     *

     * @return null|RecurringPaymentConfigurationDraft
     */
    public function getRecurringPaymentConfiguration();

    /**
     * @param ?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration
     */
    public function setRecurringPaymentConfiguration(?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration): void;
}
