<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\Builder;
use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;
use Commercetools\Base\JsonObjectModel;
use Commercetools\Base\MapperFactory;
use stdClass;

/**
 * @implements Builder<CartSetRecurringPaymentConfigurationAction>
 */
final class CartSetRecurringPaymentConfigurationActionBuilder implements Builder
{
    /**

     * @var null|RecurringPaymentConfigurationDraft|RecurringPaymentConfigurationDraftBuilder
     */
    private $recurringPaymentConfiguration;

    /**
     * <p>Value to set. If omitted, any existing value is removed and the Orders generated by the <a href="ctp:api:type:RecurringOrder">RecurringOrder</a> are created without collecting payment first.</p>
     *

     * @return null|RecurringPaymentConfigurationDraft
     */
    public function getRecurringPaymentConfiguration()
    {
        return $this->recurringPaymentConfiguration instanceof RecurringPaymentConfigurationDraftBuilder ? $this->recurringPaymentConfiguration->build() : $this->recurringPaymentConfiguration;
    }

    /**
     * @param ?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration
     * @return $this
     */
    public function withRecurringPaymentConfiguration(?RecurringPaymentConfigurationDraft $recurringPaymentConfiguration)
    {
        $this->recurringPaymentConfiguration = $recurringPaymentConfiguration;

        return $this;
    }

    /**
     * @deprecated use withRecurringPaymentConfiguration() instead
     * @return $this
     */
    public function withRecurringPaymentConfigurationBuilder(?RecurringPaymentConfigurationDraftBuilder $recurringPaymentConfiguration)
    {
        $this->recurringPaymentConfiguration = $recurringPaymentConfiguration;

        return $this;
    }

    public function build(): CartSetRecurringPaymentConfigurationAction
    {
        return new CartSetRecurringPaymentConfigurationActionModel(
            $this->recurringPaymentConfiguration instanceof RecurringPaymentConfigurationDraftBuilder ? $this->recurringPaymentConfiguration->build() : $this->recurringPaymentConfiguration
        );
    }

    public static function of(): CartSetRecurringPaymentConfigurationActionBuilder
    {
        return new self();
    }
}
