<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\Builder;
use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;
use Commercetools\Base\JsonObjectModel;
use Commercetools\Base\MapperFactory;
use stdClass;

/**
 * @implements Builder<RecurringPaymentConfigurationDraft>
 */
final class RecurringPaymentConfigurationDraftBuilder implements Builder
{
    /**

     * @var ?string
     */
    private $paymentStrategy;

    /**

     * @var ?PaymentAllocationDraftCollection
     */
    private $paymentAllocations;

    /**
     * <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     *

     * @return null|string
     */
    public function getPaymentStrategy()
    {
        return $this->paymentStrategy;
    }

    /**
     * <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     *

     * @return null|PaymentAllocationDraftCollection
     */
    public function getPaymentAllocations()
    {
        return $this->paymentAllocations;
    }

    /**
     * @param ?string $paymentStrategy
     * @return $this
     */
    public function withPaymentStrategy(?string $paymentStrategy)
    {
        $this->paymentStrategy = $paymentStrategy;

        return $this;
    }

    /**
     * @param ?PaymentAllocationDraftCollection $paymentAllocations
     * @return $this
     */
    public function withPaymentAllocations(?PaymentAllocationDraftCollection $paymentAllocations)
    {
        $this->paymentAllocations = $paymentAllocations;

        return $this;
    }


    public function build(): RecurringPaymentConfigurationDraft
    {
        return new RecurringPaymentConfigurationDraftModel(
            $this->paymentStrategy,
            $this->paymentAllocations
        );
    }

    public static function of(): RecurringPaymentConfigurationDraftBuilder
    {
        return new self();
    }
}
