<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;
use Commercetools\Base\JsonObjectModel;
use Commercetools\Base\MapperFactory;
use stdClass;

/**
 * @internal
 */
final class RecurringPaymentConfigurationDraftModel extends JsonObjectModel implements RecurringPaymentConfigurationDraft
{
    /**
     *
     * @var ?string
     */
    protected $paymentStrategy;

    /**
     *
     * @var ?PaymentAllocationDraftCollection
     */
    protected $paymentAllocations;


    /**
     * @psalm-suppress MissingParamType
     */
    public function __construct(
        ?string $paymentStrategy = null,
        ?PaymentAllocationDraftCollection $paymentAllocations = null
    ) {
        $this->paymentStrategy = $paymentStrategy;
        $this->paymentAllocations = $paymentAllocations;
    }

    /**
     * <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     *
     *
     * @return null|string
     */
    public function getPaymentStrategy()
    {
        if (is_null($this->paymentStrategy)) {
            /** @psalm-var ?string $data */
            $data = $this->raw(self::FIELD_PAYMENT_STRATEGY);
            if (is_null($data)) {
                return null;
            }
            $this->paymentStrategy = (string) $data;
        }

        return $this->paymentStrategy;
    }

    /**
     * <p>Payment Methods charged for the Orders generated by the Recurring Order, and the share of the Order total charged to each of them.</p>
     *
     *
     * @return null|PaymentAllocationDraftCollection
     */
    public function getPaymentAllocations()
    {
        if (is_null($this->paymentAllocations)) {
            /** @psalm-var ?list<stdClass> $data */
            $data = $this->raw(self::FIELD_PAYMENT_ALLOCATIONS);
            if (is_null($data)) {
                return null;
            }
            $this->paymentAllocations = PaymentAllocationDraftCollection::fromArray($data);
        }

        return $this->paymentAllocations;
    }


    /**
     * @param ?string $paymentStrategy
     */
    public function setPaymentStrategy(?string $paymentStrategy): void
    {
        $this->paymentStrategy = $paymentStrategy;
    }

    /**
     * @param ?PaymentAllocationDraftCollection $paymentAllocations
     */
    public function setPaymentAllocations(?PaymentAllocationDraftCollection $paymentAllocations): void
    {
        $this->paymentAllocations = $paymentAllocations;
    }
}
