<?php

declare(strict_types=1);
/**
 * This file has been auto generated
 * Do not change it.
 */

namespace Commercetools\Api\Models\Cart;

use Commercetools\Base\DateTimeImmutableCollection;
use Commercetools\Base\JsonObject;

interface RecurringPaymentConfiguration extends JsonObject
{
    public const FIELD_PAYMENT_STRATEGY = 'paymentStrategy';
    public const FIELD_PAYMENT_ALLOCATIONS = 'paymentAllocations';

    /**
     * <p>Determines how payment is collected for the Orders generated by the Recurring Order.</p>
     *

     * @return null|string
     */
    public function getPaymentStrategy();

    /**
     * <p>Payment Methods charged for the Orders generated by the RecurringOrder, and the share of the Order total charged to each of them.</p>
     *

     * @return null|RecurringPaymentAllocationCollection
     */
    public function getPaymentAllocations();

    /**
     * @param ?string $paymentStrategy
     */
    public function setPaymentStrategy(?string $paymentStrategy): void;

    /**
     * @param ?RecurringPaymentAllocationCollection $paymentAllocations
     */
    public function setPaymentAllocations(?RecurringPaymentAllocationCollection $paymentAllocations): void;
}
