# /etc/nginx/conf.d/nginx-newrelic.conf
upstream php-upstream {
    server php-newrelic:9001;  # Points to New Relic's PHP-FPM service
}

server {
    listen 80;
    server_name localhost;

    root /var/www/symfony/public;
    index index.php index.html;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php-upstream;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
