FROM nginx

COPY symfony.conf /etc/nginx/conf.d/default.conf

# Update the upstream configuration to point to the correct PHP service
RUN echo "upstream php-upstream { server php-datadog:9000; }" > /etc/nginx/conf.d/upstream.conf


HEALTHCHECK --interval=30s --timeout=5s \
  CMD curl -f http://localhost/ || exit 1
