FROM nginx

# Copy the NGINX configuration for Symfony
COPY symfony.conf /etc/nginx/conf.d/default.conf

# Configure upstream PHP server
RUN echo "upstream php-upstream { server php-otel:9000; }" > /etc/nginx/conf.d/upstream.conf

HEALTHCHECK --interval=30s --timeout=5s \
  CMD curl -f http://localhost/ || exit 1
