services:
  php-newrelic:
    build:
      context: ./docker/php/newrelic
      dockerfile: Dockerfile
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPNAME=PHP-SDK
    volumes:
      - .:/var/www/symfony
      - ./docker/php/.env.sample:/var/www/symfony/.env
    expose:
      - "9000"
    depends_on:
      - newrelic-php-daemon

  nginx-newrelic:
    build:
      context: ./docker/nginx/newrelic
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - php-newrelic
    volumes:
      - ./var/logs/nginx:/var/log/nginx
      - .:/var/www/symfony

  newrelic-php-daemon:
    image: newrelic/php-daemon:latest
    platform: linux/amd64
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NR_MAX_REQUEST_SIZE=1000M
    expose:
      - "31339"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://newrelic-php-daemon:31339" ]
      interval: 30s
      timeout: 10s
      retries: 5
